### ISSUE TITLE
Random failures in org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ua#130]
https://download.eclipse.org/eclipse/downloads/drops4/I20230515-0600/testresults/html/org.eclipse.ua.tests.doc_ep428I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
java.lang.NullPointerException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.testAllLinks(LinkTest.java:73)
```

https://download.eclipse.org/eclipse/downloads/drops4/I20230514-1800/testresults/html/org.eclipse.ua.tests.doc_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
Cannot read field "right" because "l" is null

java.lang.NullPointerException: Cannot read field "right" because "l" is null
at java.base/java.util.TreeMap.rotateRight(TreeMap.java:2562)
at java.base/java.util.TreeMap.fixAfterInsertion(TreeMap.java:2594)
at java.base/java.util.TreeMap.addEntry(TreeMap.java:770)
at java.base/java.util.TreeMap.put(TreeMap.java:828)
at java.base/java.util.TreeMap.put(TreeMap.java:534)
at java.base/java.util.TreeSet.add(TreeSet.java:255)
at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.checkLinks(LinkTest.java:122)
at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.lambda$0(LinkTest.java:84)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.testAllLinks(LinkTest.java:73)
```

Looks like null elements are added to indexedPagesURIs.

I will push a PR.

**Comment by iloveeclipse** [comment]
The failures just disappeared after reporting this issue. I assume they were caused by an unstable infrastructure. Closing.
