### ISSUE TITLE
LinkTest fails since Jun 14, 2023, 2:37 AM

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ua#154]
on master branch:
https://ci.eclipse.org/platform/job/eclipse.platform.ua/job/master/lastCompletedBuild/testReport/org.eclipse.ua.tests.doc.internal.linkchecker/LinkTest/testAllLinks/
```
org.junit.ComparisonFailure: expected:<[[]]> but was:<[[Link from http://127.0.0.1:33387/help/topic/org.eclipse.pde.doc.user/whatsNew/pde_whatsnew.html to Platform.php#force-https is broken: target URI http://127.0.0.1:33387/help/topic/org.eclipse.pde.doc.user/whatsNew/Platform.php#force-https doens't exist.]]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.testAllLinks(LinkTest.java:101)

```

locally:

```
org.junit.ComparisonFailure: expected:<[[]]> but was:<[[java.io.FileNotFoundException: http://127.0.0.1:60092/help/topic/org.eclipse.ua.tests/participant2.xml, java.io.FileNotFoundException: http://127.0.0.1:60092/help/topic/org.eclipse.ua.tests/participant1.xml]]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.testAllLinks(LinkTest.java:100)

```
@akurtakov is that related to PrebuiltIndexChecker?

**Comment by akurtakov** [comment]
No, see my comment https://github.com/eclipse-platform/eclipse.platform.common/commit/988e87e7683fb7cb2cab9ca20bb66d38b5ef4cc6#r117972443

**Comment by merks** [comment]
Can this really be so hard to fix?  If the test gets disabled it will probably stay that way forever...

**Comment by jukzi** [comment]
ok, who can fix this?

**Comment by iloveeclipse** [comment]
> Easiest fix is to remove the link and I can do that now if no one steps up for more.

Please just do that.

**Comment by akurtakov** [comment]
Actually having correct link was not that hard :)
