### ISSUE TITLE
128 ua.tests failed in I20220721-0550

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ua#42]
Looks like help generation **or** retrieval is broken in I20220721-0550, we have 128 ua.tests fails in I20220721-0550.

See https://download.eclipse.org/eclipse/downloads/drops4/I20220721-0550/testresults/html/org.eclipse.ua.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
http://localhost:36711/help/rtopic/org.eclipse.ua.tests/data/help/search/testnl1.xhtml?lang=de

java.io.FileNotFoundException: http://localhost:36711/help/rtopic/org.eclipse.ua.tests/data/help/search/testnl1.xhtml?lang=de
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
at java.base/java.net.URL.openStream(URL.java:1117)
at org.eclipse.ua.tests.help.remote.RemoteTestUtils.readFromURL(RemoteTestUtils.java:60)
at org.eclipse.ua.tests.help.remote.RemoteTestUtils.getRemoteContent(RemoteTestUtils.java:44)
at org.eclipse.ua.tests.help.remote.ContentServletTest.testContentInDeLocale(ContentServletTest.java:70)
```

Also see the fail in 
https://download.eclipse.org/eclipse/downloads/drops4/I20220721-0550/testresults/html/org.eclipse.ua.tests.doc_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
expected:<[]> but was:<[java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/guide/product_extension.htm, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/guide/jface.htm, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/guide/login_extensions.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_debug_ui_debugModelPresentations.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/jface/text/hyperlink/package-summary.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_ui_preferencePages.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_debug_ui_contextViewBindings.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/filebuffers/package-summary.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/databinding/observable/set/package-summary.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/porting/4.9/faq.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/porting/4.8/incompatibilities.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_equinox_http_registry_resources.html, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/guide/wrkAdv_undo_ide.htm, java.io.FileNotFoundException: http://127.0.0.1:43425/help/topic/org.eclipse.platform.doc.isv/guide/st_text_types.htm, java.io.FileNotFoundException: 

...

```

**Comment by akurtakov** [comment]
Running the tests locally there is tons of:
```
javax.servlet.ServletException: The init() method was never called.
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServiceObject.<init>(HttpServiceRuntimeImpl.java:1366)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.<init>(HttpServiceRuntimeImpl.java:1429)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl.registerHttpServiceServlet(HttpServiceRuntimeImpl.java:865)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl$3.run(HttpServiceImpl.java:137)
```
@tjwatson Any hint what this LegacyServlet means? This sounds like smth help system should have moved away from years ago.
@HannesWell I agree with @iloveeclipse  that it's mostly like caused by this equinox change.

**Comment by iloveeclipse** [comment]
One goes over all commits in all platform repositories and check which were made in last IBuild only (ok, last 3 builds because two builds failed). From these, one selects only related and looking on the failures, the equinox PR seems to be the "hottest" candidate.

**Comment by iloveeclipse** [comment]
> Running the tests locally there is tons of:

Do you run them via maven or from IDE? I can't see any fails if running from IDE in debugger. 
Do we have some maven test specific issues, like missing dependencies etc?

This could be related then to https://github.com/eclipse-equinox/equinox/pull/75, which also appeared first in this build.

**Comment by HannesWell** [comment]
When I run `org.eclipse.ua.tests.AllTests` in my IDE about 50 tests fail, but that failure seems unrelated to the I-build failure (other code locations and messages that indicate the root cause to be my location).

Furthermore I went through again through all the changes of https://github.com/eclipse-equinox/equinox/pull/45 and could not find anything suspicious. 

Could this maybe be caused by some infrastructure issue?

> This could be related then to [eclipse-equinox/equinox#75](https://github.com/eclipse-equinox/equinox/pull/75), which also appeared first in this build.

That change should not affect projects outside the equinox-project.

**Comment by iloveeclipse** [comment]
> Could this maybe be caused by some infrastructure issue?

In fact, we see **today** some network errors on eclipse.org: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1572

Related?

**Comment by HannesWell** [comment]
> Related?

Looks like not related.
Those tests are still constantly failing...
https://download.eclipse.org/eclipse/downloads/drops4/I20220722-1800/testresults/html/org.eclipse.ua.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

**Comment by iloveeclipse** [comment]
@akurtakov : how did you reproduce the fails?

**Comment by iloveeclipse** [comment]
OK, I believe that's a dependency issue. After removing org.apache.commons.fileupload bundle from my target platform I see the test fails.

I see now same errors logged as ones during official tests:
https://download.eclipse.org/eclipse/downloads/drops4/I20220722-1800/testresults/ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11/org.eclipse.ua.tests.doc.AllTests.txt

https://download.eclipse.org/eclipse/downloads/drops4/I20220722-1800/testresults/ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11/org.eclipse.ua.tests.AllTests.txt


```
!ENTRY org.eclipse.equinox.http.servlet 4 0 2022-07-23 00:20:49.427
!MESSAGE org.eclipse.equinox.http.servlet.internal.multipart.MultipartSupportFactory: Provider org.eclipse.equinox.http.servlet.internal.multipart.MultipartSupportFactoryImpl could not be instantiated
!STACK 0
java.util.ServiceConfigurationError: org.eclipse.equinox.http.servlet.internal.multipart.MultipartSupportFactory: Provider org.eclipse.equinox.http.servlet.internal.multipart.MultipartSupportFactoryImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at org.eclipse.equinox.http.servlet.internal.registration.ServletRegistration.<clinit>(ServletRegistration.java:40)
	at org.eclipse.equinox.http.servlet.internal.context.ContextController.doAddServletRegistration(ContextController.java:478)
	at org.eclipse.equinox.http.servlet.internal.context.ContextController.addServletRegistration(ContextController.java:435)
	at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.addingService(ContextServletTrackerCustomizer.java:81)
	at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.addingService(ContextServletTrackerCustomizer.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:123)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:961)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:937)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:874)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:262)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:500)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:519)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1047)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl.registerHttpServiceServlet(HttpServiceRuntimeImpl.java:891)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl$3.run(HttpServiceImpl.java:137)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl$3.run(HttpServiceImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl.registerServlet(HttpServiceImpl.java:134)
	at org.eclipse.equinox.http.registry.internal.HttpRegistryManager.registerServlet(HttpRegistryManager.java:261)
	at org.eclipse.equinox.http.registry.internal.HttpRegistryManager.addServletContribution(HttpRegistryManager.java:143)
	at org.eclipse.equinox.http.registry.internal.ServletManager.added(ServletManager.java:137)
	at org.eclipse.equinox.http.registry.internal.ExtensionPointTracker.open(ExtensionPointTracker.java:80)
	at org.eclipse.equinox.http.registry.internal.ServletManager.start(ServletManager.java:65)
	at org.eclipse.equinox.http.registry.internal.HttpRegistryManager.start(HttpRegistryManager.java:109)
	at org.eclipse.equinox.http.registry.internal.HttpServiceTracker.addingService(HttpServiceTracker.java:61)
	at org.eclipse.equinox.http.registry.internal.HttpServiceTracker.addingService(HttpServiceTracker.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
	at org.eclipse.equinox.http.registry.internal.HttpServiceTracker.open(HttpServiceTracker.java:45)
	at org.eclipse.equinox.http.registry.internal.Activator.addingService(Activator.java:63)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
	at org.eclipse.equinox.http.registry.internal.Activator.start(Activator.java:41)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.help.internal.server.JettyHelpServer.checkBundle(JettyHelpServer.java:132)
	at org.eclipse.help.internal.server.JettyHelpServer.start(JettyHelpServer.java:119)
	at org.eclipse.help.internal.server.WebappManager.start(WebappManager.java:41)
	at org.eclipse.ua.tests.help.webapp.HelpServerInterrupt$ServerStarter.run(HelpServerInterrupt.java:43)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/fileupload/FileUploadException
	at org.eclipse.equinox.http.servlet.internal.multipart.MultipartSupportFactoryImpl.<clinit>(MultipartSupportFactoryImpl.java:23)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 65 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.fileupload.FileUploadException cannot be found by org.eclipse.equinox.http.servlet_1.7.300.v20220720-2012
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 71 more
```

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ua/pull/43. I have no idea if that fixes the problem or not, but looks like maven/tycho don't include optional imports from dependencies of the bundles under tests. 

May be there is some magic flag needed in some arcane maven build files to enforce that, or may be something completely different is broken now.

**Comment by iloveeclipse** [comment]
Could be related to https://github.com/eclipse/tycho/issues/1181 ?

**Comment by iloveeclipse** [comment]
I will trigger SDK build now to validate if #43 fixes the problem in SDK tests. At least in Jenkins all tests were fine.

**Comment by iloveeclipse** [comment]
> I will trigger SDK build now to validate if #43 fixes the problem in SDK tests.

Yep, that worked. Remaining failure in ui.tests.doc is covered by #44 .

The question remains: which change (tycho ? pom files?) caused regression and if there is something else broken/need to be fixed. 

For me it looks like optional dependencies from direct dependencies of the test bundles aren't added anymore to the constructed target platform. 

In this concrete case it was **org.eclipse.equinox.http.servlet** that imported org.apache.commons.fileupload needs this package but it is marked as optional so probably not added to the test runtime dependencies. But the dependency chain is more complicated:

- org.eclipse.ua.tests bundle requires org.eclipse.help.base bundle
- org.eclipse.help.base bundle **optionally** imports org.eclipse.equinox.http.jetty package
- org.eclipse.equinox.http.jetty bundle imports org.eclipse.equinox.http.servlet package
- org.eclipse.equinox.http.servlet **optionally** imports org.apache.commons.fileupload package

So somewhere between  org.eclipse.ua.tests and org.eclipse.equinox.http.servlet the optionally imported org.apache.commons.fileupload  was "lost".

**Comment by laeubi** [comment]
> In this concrete case it was **org.eclipse.equinox.http.servlet** that imported org.apache.commons.fileupload needs this package but it is marked as optional

As noted elsewhere, marking a package/bundle as **optional** means you can work without it and the OSGi resolver is allowed to not bind that package, if that's not the case it is simply not optional.

**Comment by iloveeclipse** [comment]
It is optional for org.eclipse.equinox.http.servlet, but obviously not for the test. 
The question for me is: what exactly changed now, and if that may cause other issues.
The test code itself isn't changed and was running fine before.

**Comment by laeubi** [comment]
> The question for me is: what exactly changed now, and if that may cause other issues.

It might be that some other dependency required by the test either explicitly or implicitly has pulled in the dependency and then this was changed and now has "broken" the test.

From the stacktrache it seems that `org.eclipse.equinox.http.servlet.internal.multipart.MultipartSupportFactoryImpl` is the culprit and should explicitly require `org.apache.commons.fileupload` ...

**Comment by iloveeclipse** [comment]
All related test fails are gone in https://download.eclipse.org/eclipse/downloads/drops4/I20220723-1800/testResults.php

**Comment by HannesWell** [comment]
> All related test fails are gone in https://download.eclipse.org/eclipse/downloads/drops4/I20220723-1800/testResults.php
>
Great. Thank you Andrey for fixing the tests.

I looked a bit about some past changes but didn't find one that removes a dependency to `org.apache.commons.fileupload`. So it is probably some transitive dependency. Any since it is working now. That should be fine.

Furthermore I share Christoph's analysis and think that is right, regarding the cause of the failure and regarding that  `org.eclipse.equinox.http.servlet` is not prepared to handle absent `org.apache.commons.fileupload(.disk|servlet)` packages. So unless the code-paths that reference classes from those packages are not possible if those packages are not present, I think  those packages probably should not be optional.
The optional dependency was introduced in 57395de0973cb0e0638525746aaaeb8aac03b352.

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-equinox/equinox/issues/88 :-(
